version: '2.1'

services:

  app:
    build: .
    depends_on:
      - pgsql
    links:
      - pgsql
    ports:
      - 8000:8000
    restart: always
  pgsql:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: snipt
      POSTGRES_USER: snipt
      POSTGRES_DB: snipt
      POSTGRES_DB_SCHEMA: snipt
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
