version: "3.6"
services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      ELASTICSEARCH: ${ELASTICSEARCH}
      ELASTICSEARCH_USE_SSL: ${ELASTICSEARCH_USE_SSL}
      ELASTICSEARCH_VERIFY_CERTS: ${ELASTICSEARCH_VERIFY_CERTS}
      ELASTICSEARCH_USER: ${ELASTICSEARCH_USER}
      ELASTICSEARCH_PASS: ${ELASTICSEARCH_PASS}
    restart: unless-stopped
