version: "2.4"
services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      ELASTICSEARCH: ${ELASTICSEARCH}
    networks:
      - esnet
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms64m -Xmx64m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  # kibana:
  #   image: docker.elastic.co/kibana/kibana-oss:6.3.0
  #   environment:
  #     SERVER_NAME: ${KIBANA_SERVER_NAME}
  #     ELASTICSEARCH_URL: ${KIBANA_ELASTICSEARCH_URL}
  #   ports:
  #       - 5601:5601
  #   volumes:
  #     - ./data/kibana:/usr/share/kibana/data
  #   networks:
  #     - esnet
  #     depends_on:
  #     - elasticsearch

networks:
  esnet:
