version: "3.6"
services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      ELASTICSEARCH: ${ELASTICSEARCH}
    networks:
      - esnet
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.2
    environment:
      discovery.type: single-node
      cluster.name: notes-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms196m -Xmx196m"
    # mem_limit: 100m
    # cpu_count: 1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  # kibana:
  #   image: docker.elastic.co/kibana/kibana-oss:6.3.0
  #   environment:
  #     SERVER_NAME: ${KIBANA_SERVER_NAME}
  #     ELASTICSEARCH_URL: ${KIBANA_ELASTICSEARCH_URL}
  #   ports:
  #       - 5601:5601
  #   volumes:
  #     - ./data/kibana:/usr/share/kibana/data
  #   networks:
  #     - esnet
  #   depends_on:
  #     - elasticsearch

networks:
  esnet:
