version: "3.6"
services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      ELASTICSEARCH: ${ELASTICSEARCH}
      FLASK_ENV: ${FLASK_ENV}
      DB_PROVIDER: ${DB_PROVIDER}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_HOST: ${MONGO_HOST}
    networks:
      - notes-net
    depends_on:
      - mongo
      - elasticsearch
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      discovery.type: single-node
      cluster.name: notes-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms196m -Xmx196m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - notes-net
    restart: unless-stopped
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    networks:
      - notes-net
    restart: unless-stopped

networks:
  notes-net:
